name: BloodMoon
version: 0.15
main: uk.co.jacekk.bukkit.bloodmoon.BloodMoon
load: startup
commands:
    bloodmoon:
        description: Toggles the bloodmoon for the current world.
        usage: /<command> <start/stop> [world_name]
        aliases: [bm, blood]